###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 28081
  servlet:
    context-path: /

###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework: warn
    org.clever: debug

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: clever-notification-demo
  aop.proxy-target-class: true

  servlet: #------------------------------------------------------------ 文件上传配置
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

  http: #------------------------------------------------------------------ http配置
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: true

  jackson: #------------------------------------------------------------ jackson配置
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  resources: #------------------------------------------------ html、js、css 静态资源
    chain:
      cache: true
      gzipped: true
    cache:
      period: 31536000s
    static-locations: ['classpath:/static/']

  cloud: #------------------------------------------------------------ Spring Cloud
    consul:
      enabled: false
      host: '127.0.0.1'
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: wuhan
        instance-group: svc
        tags:
        - serviceName=${spring.application.name}
        health-check-path: '/actuator/health'
        health-check-interval: 1s

###################################################################################
### management配置
###################################################################################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - health
        - info
        - env
        - metrics
        - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      root: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 5s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 3s, 4s, 5s, 10s, 15s, 20s, 30s, 50s

###################################################################################
### Feign配置
###################################################################################
# CommonClientConfigKey 实现
clever-notification-server:
  ribbon:
    listOfServers: '127.0.0.1:28080'

















